#+title: Getting Gratitude Entries

* Intro
In my last post (ADD LINK), I reflected on the entries in my gratitude journal and my takeaways from the year. I had a similar post in 2021 (ADD LINK). In that post, I also included some details of how I got access to all of my entries (both how I attempted (ADD LINK) and how I /actually/ got it to work (ADD LINK)). This year I decided to cover how I accessed in a separate post.

I am using org-roam's dailies (ADD LINK) feature as a place to write down three things for which I am grateful for or excited about each day. I enter them as an ordred list under the same header, something like:

#+begin_src org-mode
\* Grateful or Excited About
#+begin_comment
What are 3 things I am grateful for or excited about.
#+end_comment

1. Thing 1
2. Thing 2
3. Thing 3
#+end_src

In my 2021 post, I tried using the org-elements API (ADD LINK), but ended up instead using ~sed~. Wanting to put my ~elisp~ skills to the test a year later, I investigated the org-elements route again this year. This time, successfully.
* Script

** Full script
** Using the org-elements API
* Comparing with last year
** Code comparison
** Performance
* Takeaways
** Using headlines
** Plan for next year
