#+title: One On One Doc

Prior to my first one-on-one my new manager granted me access to a shared one-on-one document. Within this document, they include a number of questions about my professional background and aspirations as well as some my personality and preferences. This is a practice I plan to steal and use with future managers (or reports, should I move into management again).

While not a replacement for actually /talking/ about these ideas or having a [[https://www.radicalcandor.com/problem-career-conversations/][career conversation]], these questions provide something akin to a trading care card for my career—the reader can see my stats, strengths, and weaknesses. Some sample questions include:

- what are technologies that you've worked with in the past
- what are you interested in learning more about
- what are your strengths
- what are your weaknesses

As the employee  this gives me some time to sit and think about these questions, providing better answers than I may if I were to be asked on the spot. I also have a "living document." As my career evolves, I can adjust my experiences or interests. This can also be used as an introduction to a new manager, should the need arise.

I think this is also valuable from the manager's point of view as it becomes infinitely easier to support someone in their career when they know what they want. Now only that, but have a cheat sheet you can look to. Having led teams in the past, it can be all too easy to forget some of the background skills your team comes in with if they aren't using it every day or to always have their career aspirations top of mind. Again, this is not a replacement for having real conversations in which you listen, but in the spirit of [[https://earnworthy.com/david-allen-quote/][Getting Things Done]] and [[https://www.buildingasecondbrain.com/][Building a Second Brain]], I think it is okay to acknowledge that your brain cannot store everything. Juggling multiple reports and your own career is an extremely difficult task. I am grateful for a manager that is using tools like this to help support me during my career.
